### ISSUE TITLE
Missing elements

### ISSUE THREAD

**Issue by josephven** [condero/dokuwiki-toggle#1]
Hello,
It is a really useful plugin.
When I uploaded the file (from URL or ZIP), the "-" in name failed, so I renamed the folder just with "toggle".
Also I added a "plugin.info.txt" with content:
base   toggle
author condero Aktiengesellschaft
email  info@condero.com
date   2016-11-28
name   DokuWiki Toggle Plugin
desc   This plugin toggles visibility of text

After this changes, the plugin started to work properly!
Thanks!

**Comment by fjd** [comment]
Thanks for the feedback - we have just updated
